apiVersion: v1
kind: Pod
metadata:
  name: db-news
  labels:
    app: db-news
spec:
  containers:
    - name: db-news-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap # nome do configmap criado, nao eh pelo label
        # para pegar o configmap uma env var especifica
        #- name: MYSQL_ROOT_PASSWORD
        #  valueFrom:
        #    configMapKeyRef:
        #      name: db-configmap
        #      key: MYSQL_ROOT_PASSWORD