version: '3.8'
services:
  mysql_store_db:
    container_name: mysql_store_db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_DATABASE=store