apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels: # usadas para comunicacao entre o svc e o pod
    app: segundo-pod
    #chave-qualquer: meu-pod2
spec:
  containers:
    - name: pod-2
      image: ngnix:latest
      ports:
        - containerPort: 80
