apiVersion: v1
kind: Service
metadata:
  name: svc-pod2
spec:
  type: ClusterIP # permite comunicacao interna entre os pods do cluster
  selector:
    app: segundo-pod
  ports:
    - port: 80
      #targetPort: 80
      #targetPort é opcional quando a porta de entrada (port) é igual a porta de saída (targetPort) 
